x-configuration: &CONFIGURATION
  volumes:
    - ~/srcML:/srcML:ro
    - ~/Data:/Data
    - ~/Builds:/Builds
  working_dir: /srcML-build
  command: bash -c "${COMPOSE_COMMAND-
    cmake -G Ninja --preset gcc-release -DBUILD_PARSER_TESTS=ON -DBUILD_CLIENT_TESTS=ON -DBUILD_LIBSRCML_TESTS=OFF -DBUILD_EXAMPLES=OFF /srcML;
    ninja install;
    ldconfig;
    srcml --version;
    ctest -j 6 --timeout 10;
    ninja gen_parser_tests;
    ninja run_parser_tests; }
    ${COMPOSE_APPEND- }"

services:

  ubuntu_24.04:
    image: srcml/ubuntu:24.04
    environment:
      - PLATFORM=ubuntu_24.04
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  ubuntu_23.10:
    image: srcml/ubuntu:23.10
    environment:
      - PLATFORM=ubuntu_23.10
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  ubuntu_22.04:
    image: srcml/ubuntu:22.04
    environment:
      - PLATFORM=ubuntu_22.04
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  ubuntu_20.04:
    image: srcml/ubuntu:20.04
    environment:
      - PLATFORM=ubuntu_20.04
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  fedora_41:
    image: srcml/fedora:41
    environment:
      - PLATFORM=fedora_41
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  fedora_40:
    image: srcml/fedora:40
    environment:
      - PLATFORM=fedora_40
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  fedora_39:
    image: srcml/fedora:39
    environment:
      - PLATFORM=fedora_39
      - VERSION=${VERSION}
    <<: *CONFIGURATION

  fedora_38:
    image: srcml/fedora:38
    environment:
      - PLATFORM=fedora_38
      - VERSION=${VERSION}
    <<: *CONFIGURATION
